from django.contrib import admin
from django.urls import path

from .views import admin_views
from . import views
urlpatterns = [
    path('', views.get_index, name='index'),
    path('catalog/', views.get_catalog, name='catalog'),
    path('cart/', views.get_cart, name='cart'),
    path('payment/', views.get_payment, name='payment'),
    path('login/', views.get_login, name='login'),
    path('forgotpassword/', views.get_forgotpassword, name='forgotpassword'),
    path('register/', views.get_register, name='register'),
    path('about/', views.get_about, name='aboutUs'),
    path('account/', views.get_account, name='account'),
    path('info/', views.get_info, name='info'),
    path('changepw/', views.get_changepw, name='changepw'),
    path('history/', views.get_history, name='history'),
    path('logout/', views.get_logout, name='logout'),
    path('product/<int:product_id>/', views.get_product, name='product'),
    path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('shippingPolicies/', views.get_shippingPolicies, name='shippingPolicies'),
    path('termOfUse/', views.get_termOfUse, name='termOfUse'),
    path('warrantyPolicies/', views.get_warrantyPolicies, name='warrantyPolicies'),
    path('help/', views.get_help, name='help'),
    path('adminPage1/', views.get_adminPage1, name='adminPage1'),
    path('adminPage2/', views.get_adminPage2, name='adminPage2'),
    path('quan-ly/them-san-pham/', views.add_product, name='add_product'),
    path('quanly/delete-product/<int:product_id>/', views.delete_product, name='delete_product'),
    path('quan-ly/sua-san-pham/<int:product_id>/', views.edit_product, name='edit_product'),
    path('adminPage3/', views.get_adminPage3, name='adminPage3'),
    path('adminPage4/', views.get_adminPage4, name='adminPage4'),
    path('adminPage5/', views.get_adminPage5, name='adminPage5'),
    path('adminPage6/', views.get_adminPage6, name='adminPage6'),
    path('quan-ly/xoa-danh-gia/<int:review_id>/', views.delete_review, name='delete_review'),
    path('adminPage7/', views.get_adminPage7, name='adminPage7'),
    path('adminPage8/', views.get_adminPage8, name='adminPage8'),
    path('add_discount/', views.add_discount, name='add_discount'),
    path('delete_discount/<int:promo_id>/', views.delete_discount, name='delete_discount'),
    path('cart/prepare/', order_views.prepare_checkout, name='prepare_checkout'),
    path('checkout/', order_views.checkout_view, name='checkout'),
    path('apply_coupon/', order_views.apply_coupon, name='apply_coupon'),
    path('remove_coupon/', order_views.remove_coupon, name='remove_coupon'),
    path('process/', order_views.process_checkout, name='process_checkout'),
    path('remove_cart_item/', views.remove_cart_item, name='remove_cart_item'),
    path('remove_all_cart_items/', views.remove_all_cart_items, name='remove_all_cart_items'),
    path('search/', views.get_search, name='search'),
    path('delete_account/<int:user_id>/', views.delete_account, name='delete_account'),
    path('add_account/', views.add_account, name='add_account'),
    path('add_banner/', views.add_banner, name='add_banner'),
    path('update_banner/', views.update_banner, name='update_banner'),
    path('payment/qr/<int:order_id>/', views.payment_qr, name='payment_qr'),
    path('order/cancel/<int:order_id>/', views.cancel_order, name='cancel_order'),
    path('order/confirm/<int:order_id>/', views.confirm_order, name='confirm_order'),
    path('register/', views.get_register, name='register'),
    path('verify-otp/', views.verify_otp, name='verify_otp'),
    path('resend-otp/', views.resend_otp, name='resend_otp'),
]
