# Generated by Django 5.2.8 on 2026-01-02 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotions',
            options={'managed': True},
        ),
    ]
