# Generated by Django 5.2.8 on 2025-12-03 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='users',
            table_comment='users table',
        ),
    ]
