# Generated by Django 5.2.8 on 2025-12-21 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_initial'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='users',
            table_comment=None,
        ),
    ]
